name: CRPI_DMC
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pytorch=2.4.1
  - torchvision=0.20.0
  - torchaudio=2.4.1
  - pytorch-cuda=12.4
  - ffmpeg
  - pip:
      - dm-control==1.0.23
      - hydra-core==1.1.0
      - hydra-submitit-launcher==1.1.5
      - imageio==2.33.1
      - mujoco==3.2.3
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - termcolor==2.4.0
      - tensorboard==2.14.0
      - tqdm==4.67.1
